### ISSUE TITLE
Missing module neural_lib?

### ISSUE THREAD

**Issue by heshenghuan** [hltcoe/golden-horse#11]
When I try to run the training process, there was an error "**ImportError: No module named neural_lib**". I cannot find a module named neural_lib. But in the old version, I can find a module named "neural_lib_crf".

I tried to import the neural_lib_crf, but the program still can not run. And the error message is "**ImportError: No module named neural_architectures**".

It seems that the current code has some missing modules.

**Comment by VioletPeng** [comment]
Nice catch. I just added the missing files and tested in a clean environment, should be ok now.
