### ISSUE TITLE
annotation  problem 

### ISSUE THREAD

**Issue by harryhaos** [hltcoe/golden-horse#5]
In file "weiboNER_2nd_conll.dev", is following annotation make sense? 

官0	O
方1	O
微0	O
博1	O
卫2	B-PER.NAM
庄3	I-PER.NAM
大0	I-PER.NAM
人1	I-PER.NAM
果0	O
然1	O

How can I split it to word with annotation?

**Comment by VioletPeng** [comment]
Hi, the numbers attached to the characters denote the relative position of the character in a word. So this sentence should convert to 官方 微博卫庄 大人 果然

The segmentation is generated automatically by jieba, so it could be wrong (in this sentence, I think it is not exactly correct). You can also ignore these numbers and do your own segmentation with any segmenter you like. This representation enables us to take advantages of the character-positional embeddings, which worked well in our experiments. We also provided the pre-trained character embeddings and character-positional embeddings in this repo under the directory "embeddings".

Does this answers your question?

**Comment by harryhaos** [comment]
Yes, thanks a lot!
