### ISSUE TITLE
NameError: global name 'get_tokenizations' is not defined

### ISSUE THREAD

**Issue by jfrance1** [hltcoe/golden-horse#8]
Coming from:
sighan_ner.py, ~line 205, in read_concrete
tokenizations = get_tokenizations(comm)

Tag @cjmay , you're it.

**Comment by ccmaymay** [comment]
Oh, I'm sorry.  My guess is `get_tokenizations` was incidentally pulled in by the star import from an old version of... `concrete.inspect`, maybe?  It's defined in `concrete.util` and would ideally be imported from there, I'll add a pull request to that effect.

**Comment by ccmaymay** [comment]
I was getting this mixed up with `get_tokens`... `get_tokenizations` was definitely in `concrete.inspect` previously, and will be available in `concrete.util` in the future.  I added a merge request to fix this in golden-horse in the time being.  Sorry!

**Comment by ccmaymay** [comment]
PR: https://github.com/hltcoe/golden-horse/pull/9
